#!/usr/bin/env bash
set -euo pipefail

ROS_DISTRO_NAME="${ROS_DISTRO_NAME:-humble}"
SERVO_BACKEND="${DELTA_SERVO_BACKEND:-auto}"
ARM1_PIN="${DELTA_SERVO_PIN_ARM1:-12}"
ARM2_PIN="${DELTA_SERVO_PIN_ARM2:-13}"
ARM3_PIN="${DELTA_SERVO_PIN_ARM3:-18}"
SERVO_PULSE_MIN_US="${DELTA_SERVO_PULSE_MIN_US:-1000}"
SERVO_PULSE_MAX_US="${DELTA_SERVO_PULSE_MAX_US:-2000}"
POSITION_DEADBAND_MM="${DELTA_POSITION_DEADBAND_MM:-0.75}"
THETA_DEADBAND_DEG="${DELTA_THETA_DEADBAND_DEG:-0.8}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "/opt/ros/${ROS_DISTRO_NAME}/setup.bash"
if [ -f "${SCRIPT_DIR}/install/setup.bash" ]; then
  source "${SCRIPT_DIR}/install/setup.bash"
fi

export DELTA_SERVO_BACKEND="${SERVO_BACKEND}"
export DELTA_SERVO_PIN_ARM1="${ARM1_PIN}"
export DELTA_SERVO_PIN_ARM2="${ARM2_PIN}"
export DELTA_SERVO_PIN_ARM3="${ARM3_PIN}"
export DELTA_SERVO_PULSE_MIN_US="${SERVO_PULSE_MIN_US}"
export DELTA_SERVO_PULSE_MAX_US="${SERVO_PULSE_MAX_US}"
export DELTA_POSITION_DEADBAND_MM="${POSITION_DEADBAND_MM}"
export DELTA_THETA_DEADBAND_DEG="${THETA_DEADBAND_DEG}"

ros2 run delta_robot_ros rpi_robot_node
